// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaoBhOlPW5Zbrlb12xGXSNKzrqA-Qiyc8',
    appId: '1:557743982531:web:dd319becac74373f979f76',
    messagingSenderId: '557743982531',
    projectId: 'baby-name-finder-93f67',
    authDomain: 'baby-name-finder-93f67.firebaseapp.com',
    storageBucket: 'baby-name-finder-93f67.appspot.com',
    measurementId: 'G-K69WLRQR8L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUBllnixtN-RNzUhllwJcIE3fZr0wsCjY',
    appId: '1:557743982531:android:4c9e75887cee36ca979f76',
    messagingSenderId: '557743982531',
    projectId: 'baby-name-finder-93f67',
    storageBucket: 'baby-name-finder-93f67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7GDB3Z5492YfYvS0-RGYOveqW_VvmQRQ',
    appId: '1:557743982531:ios:189ef3bd227d5779979f76',
    messagingSenderId: '557743982531',
    projectId: 'baby-name-finder-93f67',
    storageBucket: 'baby-name-finder-93f67.appspot.com',
    iosBundleId: 'com.example.babyname',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7GDB3Z5492YfYvS0-RGYOveqW_VvmQRQ',
    appId: '1:557743982531:ios:189ef3bd227d5779979f76',
    messagingSenderId: '557743982531',
    projectId: 'baby-name-finder-93f67',
    storageBucket: 'baby-name-finder-93f67.appspot.com',
    iosBundleId: 'com.example.babyname',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaoBhOlPW5Zbrlb12xGXSNKzrqA-Qiyc8',
    appId: '1:557743982531:web:dd4a15ca9f06cd4b979f76',
    messagingSenderId: '557743982531',
    projectId: 'baby-name-finder-93f67',
    authDomain: 'baby-name-finder-93f67.firebaseapp.com',
    storageBucket: 'baby-name-finder-93f67.appspot.com',
    measurementId: 'G-C9LLTY24JX',
  );
}
